title: "Suengjae Hong<br><br>홍승재의 블로그"
description: This webpage is a collection of my interests and projects in the fields of social network analysis, data science, text analysis, and machine learning. 

markdown: kramdown

![image](http://res.cloudinary.com/djemws8d8/image/upload/c_scale,w_150/v1527602031/KakaoTalk_20180529_225037917.jpg)

show_downloads: false
theme: jekyll-theme-minimal
